apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dremio-executor
  namespace: dremio-ns
  labels:
    app: dremio-executor
spec:
  serviceName: "dremio-service"
  replicas: 2  # Apenas 1 Executor
  selector:
    matchLabels:
      app: dremio-executor
  template:
    metadata:
      labels:
        app: dremio-executor
    spec:
      securityContext:
        runAsUser: 999  # UID do usuário dremio
        runAsGroup: 999  # GID do grupo dremio
        fsGroup: 999  # Permissões para volumes montados
      containers:
      - name: dremio-oss
        image: dremio/dremio-oss:latest
        ports:
        - containerPort: 31010  # Porta para conexão JDBC/ODBC
        - containerPort: 9047   # Interface web (pode ser desativada no Executor)
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp  # Apenas diretório temporário
        env:
        - name: DREMIO_ROLE
          value: "executor"  # Define como Executor
        - name: TZ
          value: "America/Campo_Grande"
        - name: JAVA_OPTS
          value: "-Duser.timezone=America/Campo_Grande"
        - name: DREMIO_JAVA_SERVER_EXTRA_OPTS
          value: "-Dpaths.dist=file:///opt/dremio/data/dist"  
        resources:
          requests:
            memory: "5Gi"
            cpu: "2"
          limits:
            memory: "6Gi"
            cpu: "2.5"
  volumeClaimTemplates:
  - metadata:
      name: tmp-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
