apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dremio-executor
  namespace: dremio-ns
  labels:
    app: dremio-executor
spec:
  serviceName: "dremio-service"
  replicas: 4
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain  # Mantém os volumes após a exclusão do StatefulSet
    whenScaled: Retain
  selector:
    matchLabels:
      app: dremio-executor
  template:
    metadata:
      labels:
        app: dremio-executor
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: dremio-oss
        image: dremio/dremio-oss:latest
        ports:
        - containerPort: 31010  # Porta JDBC/ODBC
        - containerPort: 9047   # Interface web (pode ser desativada no Executor)
        volumeMounts:
        - name: data-volume
          mountPath: /opt/dremio/data  
        - name: acceleration-volume
          mountPath: /opt/dremio/acceleration
        - name: tmp-volume
          mountPath: /tmp
        - name: dremio-conf-volume
          mountPath: /opt/dremio/conf/dremio.conf
          subPath: dremio.conf
        env:
        - name: DREMIO_ROLE
          value: "executor"
        - name: TZ
          value: "America/Campo_Grande"
        - name: JAVA_OPTS
          value: "-Duser.timezone=America/Campo_Grande"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "5Gi"
            cpu: "2.5"
      volumes:
      - name: dremio-conf-volume
        configMap:
          name: dremio-exctor-conf
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi  
  - metadata:
      name: tmp-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: acceleration-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
