apiVersion: v1
kind: Service
metadata:
  name: dremio-service
  namespace: dremio-ns
  labels:
    app: dremio-coordinator  # Associa ao coordinator
spec:
  type: NodePort  # Acesso externo
  selector:
    app: dremio-coordinator  # O serviço "aponta" para o Coordinator
  ports:
  - name: web
    protocol: TCP
    port: 9047       # Porta interna
    targetPort: 9047 # Porta do container
    nodePort: 30047  # Porta externa
  - name: jdbc
    protocol: TCP
    port: 31010
    targetPort: 31010
    nodePort: 30010
