apiVersion: v1
kind: Service
metadata:
  name: dremio-coordinator
  namespace: dremio-ns
spec:
  clusterIP: None
  selector:
    app: dremio-coordinator
  ports:
    - name: zk
      port: 2181
      targetPort: 2181
      protocol: TCP

